services:
  - type: web
    name: photosite360-frontend
    plan: free
    env: static
    buildCommand: npm install && npx vite build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://web-production-51970.up.railway.app