services:
  - type: web
    name: photosite360-frontend
    plan: free
    env: static
    buildCommand: npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://web-production-51970.up.railway.app